### ISSUE TITLE
Packages needed for working with hipscat data

### ISSUE THREAD

**Issue by bsipocz** [nasa-fornax/fornax-images#12]
- [ ] hipscat
- [ ] lsdb
- [ ] ...

Preferably install these from pypi rather than from conda as it's expected to be more up-to-date, etc.

And the image needs to set the HIPSCAT_ALMANAC env variable for the centrally/officially provided holdings.

**Comment by zoghbi-a** [comment]
Updates done as of 11/26.
Closing this. The transition from hipscat to hats is discussed in a separate issue #17
