### ISSUE TITLE
Add notebook and code cloning to the image

### ISSUE THREAD

**Issue by bsipocz** [nasa-fornax/fornax-images#4]
Both https://github.com/fornax-navo/fornax-demo-notebooks and https://github.com/fornax-navo/fornax-cloud-access-API should be available from the platform

**Comment by bsipocz** [comment]
Hmm, interesting. And would this non-persistent space populated each time they start an instance? This setup would in fact work super nicely as updates to the repo would automatically included without any complicated plans, and documenting the need for them to copy the notebooks/save their modifications somewhere persistent is much easier than documenting how to pull updates from the repo once they have custom modifications locally..

**Comment by zoghbi-a** [comment]
The non-persistent space is populated when the image is built, not when an instance is started. So it does not really solve the issue. One Sciserver, the recommended way is to do `git pull`, or use the click the `Pull latest changes` button in the jupyterlab git extension.
I am open to better ways of doing it.

**Comment by bsipocz** [comment]
Any chance to run a script at start-up time to upgrade the checkout?

I'm not certain that the Sciserver recommendations will work seamlessly in practice, I envision that the git pull will cause all kinds of conflict troubles if they have local changes. And even in the case of a clean pull, it may lead to undebuggable situations when a user ends up with problems that we/our helpdesk cannot reproduce due to diverging versions (or they may report things just because they haven't pulled in a recent enough version, e.g a problem that I see all the time for astroquery with users stuck on an old version reporting problems that have been long fixed).

**Comment by zoghbi-a** [comment]
That is right, it can cause conflicts. The assumption though is that since it is not in a persistent space, the user starts clean with every session, so a git pull should work when they start, but not after they make changes.

I think it may work if we add `git pull` to the script that starts jupyterlab.

**Comment by bsipocz** [comment]
Oh, indeed, they start with the clean version each time. So you're right, it's less likely to conflict, but the less experienced users may still hit helpdesk due to problems in the outdated version. 
However, if updating the image itself will be a smooth and quick process, we can have a policy to redo an image and update the clone each time such a report hits helpdesk.

**Comment by zoghbi-a** [comment]
As I am updating the image to include the requested packages, I will experiment with adding a git pull to the starting script.

**Comment by bsipocz** [comment]
Thank you so much!

**Comment by zoghbi-a** [comment]
@bsipocz, you can see the updates in the Astro Dev Image. Since we don't have access to the home directory from the image. I put them in `/opt/notebooks/fornax-demo-notebooks/`, and they get updated just before jupyterlab starts. I was thinking of using .bashrc to create a soft link to that folder in the home directory. Is something like this what you had in mind?

**Comment by bsipocz** [comment]
@zoghbi-a - Just to reiterate, the idea here would be to clone the repo(s) at startup time, NOT to wrap them up in the images, therefore the users should have easy access to the latest versions and fixes available to the notebooks, documentation, or anything else we decide they should have easy access to.

**Comment by bsipocz** [comment]
The irsa notebooks would be also another set of resources that could be useful to have cloned for the users at startup.
These are tested, but may have a different set of requirements, so a couple of extra dependencies would be also useful to have.

https://github.com/Caltech-IPAC/irsa-tutorials

**Comment by zoghbi-a** [comment]
The notebooks are in the image under: `/opt/notebooks/`. There is a script that updates them with `git pull` every time the user starts a new session. These are not in the persistent space, so the user will need to copy them if they want to their changes to be saved.

**Comment by bsipocz** [comment]
Thank you!

**Comment by bsipocz** [comment]
I'm closing this now as another issue is open as a reminder to document this for the users.
